apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: monitoring
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch-service:9200"]
    path.config: /usr/share/logstash/pipeline

  logstash.conf: |
    input {
      tcp {
        port => 5000
        codec => json
      }
      udp {
        port => 5000
        codec => json
      }
    }

    filter {
      if [type] == "swifteats-logs" {
        date {
          match => [ "timestamp", "ISO8601" ]
        }
        mutate {
          remove_field => [ "@version" ]
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["elasticsearch-service:9200"]
        index => "swifteats-logs-%{+YYYY.MM.dd}"
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.10.4
        ports:
        - containerPort: 5000
          name: tcp
        - containerPort: 5000
          protocol: UDP
          name: udp
        - containerPort: 9600
          name: monitoring
        env:
        - name: LS_JAVA_OPTS
          value: "-Xmx256m -Xms256m"
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: logstash-pipeline
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
          requests:
            cpu: "0.2"
            memory: 256Mi
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-config
          items:
          - key: logstash.yml
            path: logstash.yml
      - name: logstash-pipeline
        configMap:
          name: logstash-config
          items:
          - key: logstash.conf
            path: logstash.conf

---
apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: monitoring
spec:
  selector:
    app: logstash
  ports:
  - port: 5000
    targetPort: 5000
    name: tcp
  - port: 5000
    targetPort: 5000
    protocol: UDP
    name: udp
  - port: 9600
    targetPort: 9600
    name: monitoring
  type: ClusterIP
