apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - alertmanager-service:9093

    rule_files:
      - /etc/prometheus/alert-rules.yml

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'swifteats-backend'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: swifteats-backend
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            regex: metrics
            action: keep

      - job_name: 'kubernetes-nodes'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics

  alert-rules.yml: |
    groups:
      - name: swifteats-alerts
        rules:
          # System alerts
          - alert: HighCpuUsage
            expr: swifteats_system_cpu_usage_percent > 80
            for: 5m
            labels:
              severity: warning
              service: swifteats-backend
            annotations:
              summary: "High CPU usage"
              description: "CPU usage is above 80% for more than 5 minutes."

          - alert: HighMemoryUsage
            expr: swifteats_system_memory_usage_bytes / 1024 / 1024 / 1024 > 2
            for: 5m
            labels:
              severity: warning
              service: swifteats-backend
            annotations:
              summary: "High memory usage"
              description: "Memory usage is above 2GB for more than 5 minutes."

          - alert: InstanceDown
            expr: up == 0
            for: 1m
            labels:
              severity: critical
              service: swifteats-backend
            annotations:
              summary: "Instance {{ $labels.instance }} down"
              description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

          # API alerts
          - alert: HighHttpErrorRate
            expr: sum(rate(swifteats_http_requests_total{status=~"5.."}[5m])) / sum(rate(swifteats_http_requests_total[5m])) > 0.05
            for: 2m
            labels:
              severity: critical
              service: swifteats-backend
            annotations:
              summary: "High HTTP error rate"
              description: "HTTP error rate is above 5% for more than 2 minutes."

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.47.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time=15d"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
            - name: prometheus-storage
              mountPath: /prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-storage-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage-claim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
