apiVersion: apps/v1
kind: Deployment
metadata:
  name: swifteats-backend
  namespace: swifteats-dev
  labels:
    app.kubernetes.io/name: swifteats-backend
    app.kubernetes.io/part-of: swifteats
    app.kubernetes.io/env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: swifteats-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: swifteats-backend
        app.kubernetes.io/part-of: swifteats
        app.kubernetes.io/env: dev
    spec:
      automountServiceAccountToken: false
      containers:
        - name: swifteats-backend
          image: ghcr.io/your-org/swifteats-backend:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: swifteats-backend-config
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
