apiVersion: v1
kind: Service
metadata:
  name: swifteats-backend
  namespace: swifteats-dev
  labels:
    app.kubernetes.io/name: swifteats-backend
    app.kubernetes.io/env: dev
spec:
  selector:
    app.kubernetes.io/name: swifteats-backend
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
