/**
 * Constants for performance optimization settings
 */
export const PERFORMANCE_CONSTANTS = {
  // Database connection pool settings
  DB_POOL_SIZE: 50,
  DB_POOL_MIN_SIZE: 5,
  DB_IDLE_TIMEOUT: 30000,
  DB_CONNECTION_TIMEOUT: 5000,
  DB_STATEMENT_TIMEOUT: 30000,
  DB_CONNECT_TIMEOUT: 10000,
  DB_RETRY_DELAY: 100,
  DB_MAX_RETRIES: 5,
  DB_SLOW_QUERY_THRESHOLD_MS: 100,
  
  // WebSocket settings
  WS_PING_INTERVAL: 25000,
  WS_PING_TIMEOUT: 10000,
  WS_MAX_HTTP_BUFFER_SIZE: 1e6,
  WS_MAX_CONNECTIONS: 10000,
  WS_ENABLE_COMPRESSION: true,
  
  // Compression settings
  COMPRESSION_THRESHOLD_BYTES: 1024,
  
  // Job processing settings
  JOB_CONCURRENCY: 10,
  JOB_MAX_STALLED_COUNT: 3,
  JOB_STALLED_INTERVAL: 30000,
  JOB_DEFAULT_ATTEMPTS: 3,
  JOB_BACKOFF_DELAY: 1000,
  
  // Monitoring settings
  ENABLE_PERFORMANCE_MONITORING: true,
  PERFORMANCE_MONITORING_INTERVAL_MS: 300000, // 5 minutes
  API_DETAILED_METRICS: false,
  API_SERIALIZATION_THRESHOLD_MS: 50,
  
  // Index optimization settings
  DB_ENABLE_INDEX_ANALYSIS: false,
  DB_INDEX_ANALYSIS_INTERVAL_MS: 86400000, // 24 hours
};
